### ISSUE TITLE
Ajouter un lien vers le site fraîchement créé

### ISSUE THREAD

**Issue by ponsfrilus** [epfl-si/wp-veritas#82]
Lorsqu'un utilisateur crée un nouveau site, lui proposer un lien vers l'édition de ce dernier serait sympa pour la UX : 
![image](https://user-images.githubusercontent.com/176002/86611076-75376200-bfae-11ea-8259-20aad78a3748.png)
Par exemple, remplacer "le nouveau site a été créé" par "le site [titre]() a été créé"

**Comment by GregLeBarbar** [comment]
https://github.com/epfl-si/wp-veritas/pull/84
