### ISSUE TITLE
[FR] Add the Ansible inventory host pattern to wp-veritas API

### ISSUE THREAD

**Issue by ponsfrilus** [epfl-si/wp-veritas#88]
It may save some time for the operators if they can find the inventory host pattern in the wp-veritas's API. That way, the operator can just copy it to use it with the `-l` and the `-e` wpsible args.

Filtering on this would also allow the Anslible lookup plugin "wpveritas" to fetch the entire data structure everytime — it would improve the performance a lot as all the mongodb queries are done more than 700 times...

**Comment by GregLeBarbar** [comment]
PR #118
